// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/content.ts
var mcpBooks = [
  {
    title: "\u91CD\u751F\u65AD\u4EB2\u540E\uFF0C\u5047\u5343\u91D1\u5168\u5BB6\u6094\u75AF\u4E86",
    status: "\u8FDE\u8F7D\u4E2D",
    genre: "\u73B0\u4EE3\u90FD\u5E02 \xB7 \u91CD\u751F \xB7 \u771F\u5047\u5343\u91D1 \xB7 \u65AD\u4EB2\u9006\u88AD",
    tagline: "\u5979\u628A\u6240\u6709\u7B97\u8BA1\u539F\u8DEF\u9000\u56DE\uFF0C\u628A\u4EB2\u60C5\u8FD9\u672C\u8D26\uFF0C\u4E00\u7B14\u4E00\u7B14\u6E05\u7B97\u3002",
    synopsis: "\u91CD\u6D3B\u4E00\u4E16\uFF0C\u5979\u4E0D\u518D\u662F\u90A3\u4E2A\u88AB\u8C6A\u95E8\u6536\u517B\u3001\u52AA\u529B\u8BA8\u597D\u7684\u4E56\u987A\u5047\u5343\u91D1\u3002\u6495\u7834\u6E29\u60C5\u8868\u8C61\uFF0C\u5979\u4E3B\u52A8\u65AD\u4EB2\uFF0C\u8D70\u51FA\u91D1\u4E1D\u7B3C\uFF1B\u66FE\u7ECF\u8F9C\u8D1F\u5979\u3001\u7B97\u8BA1\u5979\u7684\u5BB6\u65CF\uFF0C\u4ECE\u7591\u60D1\u5230\u5D29\u6E83\uFF0C\u4E00\u6B65\u4E00\u6B65\u6094\u5230\u53D1\u75AF\u3002\u90FD\u5E02\u8C6A\u95E8\u3001\u5BB6\u65CF\u68CB\u5C40\u3001\u804C\u573A\u7FFB\u8EAB\u3001\u611F\u60C5\u514B\u5236\u2014\u2014\u6240\u6709\u4EBA\u90FD\u4F1A\u770B\u6E05\uFF1A\u5979\u503C\u5F97\u7684\uFF0C\u4ECE\u6765\u4E0D\u662F\u6B8B\u7FB9\u51B7\u7099\u3002",
    platforms: [{ platform: "\u756A\u8304\u5C0F\u8BF4", url: null }]
  },
  {
    title: "\u7687\u5144\u9001\u6211\u53BB\u548C\u4EB2\uFF0C\u6211\u6276\u6218\u635F\u8D28\u5B50\u7834\u5C40",
    status: "\u8FDE\u8F7D\u4E2D",
    genre: "\u53E4\u8A00 \xB7 \u548C\u4EB2 \xB7 \u6743\u8C0B \xB7 \u6218\u635F\u8D28\u5B50 \xB7 \u4E71\u4E16\u7834\u5C40",
    tagline: "\u4ED6\u88AB\u5F03\u4E8E\u98CE\u96EA\uFF0C\u5979\u88AB\u9001\u5165\u654C\u56FD\uFF0C\u4E24\u4E2A\u6B8B\u5C40\uFF0C\u5408\u6210\u4E00\u76D8\u6D3B\u68CB\u3002",
    synopsis: "\u7687\u5144\u4E00\u9053\u8BCF\u4E66\uFF0C\u628A\u5979\u9001\u53BB\u548C\u4EB2\uFF0C\u585E\u5916\u98CE\u96EA\u8FCE\u63A5\u5979\u7684\uFF0C\u662F\u4E00\u4E2A\u6EE1\u8EAB\u6218\u4F24\u3001\u88AB\u672C\u56FD\u629B\u5F03\u7684\u5E74\u8F7B\u8D28\u5B50\u3002\u5979\u672C\u5E94\u8BA4\u547D\uFF0C\u4ED6\u672C\u5E94\u8D74\u6B7B\uFF1B\u5979\u504F\u8981\u770B\u770B\uFF0C\u4E24\u4E2A\u88AB\u5F03\u5B50\u7684\u4EBA\uFF0C\u80FD\u4E0D\u80FD\u5728\u654C\u56FD\u7684\u68CB\u76D8\u4E0A\uFF0C\u4E3A\u81EA\u5DF1\u6273\u56DE\u4E00\u5C40\u3002\u5BAB\u9619\u3001\u8FB9\u585E\u3001\u65CC\u65D7\u3001\u6697\u6D8C\u2014\u2014\u6743\u8C0B\u5F90\u5F90\u5C55\u5F00\uFF0C\u950B\u8292\u85CF\u4E8E\u8896\u95F4\u3002",
    platforms: [{ platform: "\u4E03\u732B\u5C0F\u8BF4", url: null }]
  }
];
var mcpPhotos = [
  {
    src: "/images/photography/vivo-3.webp",
    alt: "\u5F00\u9614\u7684\u57CE\u5E02\u8FDC\u666F\uFF0C\u5929\u7A7A\u5360\u636E\u753B\u9762\u4E0A\u90E8",
    meta: "City \xB7 Skyline",
    width: 598,
    height: 384
  },
  {
    src: "/images/photography/vivo-2.webp",
    alt: "\u7AD6\u5E45\u5149\u5F71\u8BB0\u5F55",
    meta: "Light \xB7 Frame",
    width: 597,
    height: 883
  },
  {
    src: "/images/photography/vivo-6.webp",
    alt: "\u7AD6\u5E45\u8857\u5DF7\u5149\u5F71",
    meta: "Street \xB7 Light",
    width: 597,
    height: 881
  },
  {
    src: "/images/photography/vivo-5.webp",
    alt: "\u7AD6\u5E45\u751F\u6D3B\u5207\u7247",
    meta: "Life \xB7 Slice",
    width: 600,
    height: 886
  },
  {
    src: "/images/photography/vivo-1.webp",
    alt: "\u6A2A\u5E45\u666F\u89C2\u8BB0\u5F55",
    meta: "Scene \xB7 Wide",
    width: 599,
    height: 516
  },
  {
    src: "/images/photography/vivo-4.webp",
    alt: "\u6A2A\u5E45\u5149\u5F71\u5207\u7247",
    meta: "Light \xB7 Wide",
    width: 598,
    height: 513
  }
];
var mcpSite = {
  name: "Jiang",
  headline: "Jiang \u7684\u521B\u4F5C\u4E16\u754C",
  subline: "\u5C0F\u8BF4\u521B\u4F5C\u4E0E\u98CE\u666F\u6444\u5F71",
  url: "https://genesis-glow-verse.lovable.app",
  vivoGalleryUrl: "https://gallery.vivo.com.cn/galleryh5static/index.html?#/user/661532516758",
  about: [
    "\u6211\u662F Jiang\uFF0C\u4E00\u4E2A\u559C\u6B22\u5728\u6587\u5B57\u91CC\u9020\u4E16\u754C\u3001\u5728\u5149\u5F71\u91CC\u8BB0\u8FDC\u65B9\u7684\u666E\u901A\u521B\u4F5C\u8005\u3002",
    "\u767D\u5929\u5199\u5C0F\u8BF4\uFF0C\u628A\u8111\u5B50\u91CC\u7FFB\u6D8C\u7684\u91CD\u751F\u3001\u6743\u8C0B\u3001\u90FD\u5E02\u4E0E\u53E4\u4EE3\u6545\u4E8B\u4E00\u70B9\u70B9\u843D\u6210\u7AE0\u8282\uFF0C\u76EE\u524D\u5728\u756A\u8304\u5C0F\u8BF4\u548C\u4E03\u732B\u5C0F\u8BF4\u5404\u6709\u4E00\u90E8\u4F5C\u54C1\u5728\u8FDE\u8F7D\u3002",
    "\u95F2\u4E0B\u6765\u7684\u65F6\u5019\uFF0C\u6211\u4F1A\u80CC\u7740\u76F8\u673A\u8D70\u8D70\u505C\u505C\uFF0C\u628A\u591C\u8272\u91CC\u7684\u57CE\u5E02\u3001\u6C5F\u5357\u7684\u6C34\u4E0E\u8FDC\u65B9\u5C71\u5DDD\uFF0C\u5B89\u9759\u5730\u6536\u8FDB\u753B\u9762\u3002"
  ]
};

// src/lib/mcp/tools/get-profile.ts
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get creator profile",
  description: "Get Jiang's creator profile: site headline, self-introduction, site URL and the external vivo photography gallery link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(mcpSite, null, 2) }],
    structuredContent: mcpSite
  })
});

// src/lib/mcp/tools/list-novels.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_novels_default = defineTool2({
  name: "list_novels",
  title: "List novels",
  description: "List Jiang's serialized novels with status, genre, synopsis and the reading platform (\u756A\u8304\u5C0F\u8BF4 / \u4E03\u732B\u5C0F\u8BF4). Reading URLs are null when not yet published on the site.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(mcpBooks, null, 2) }],
    structuredContent: { novels: mcpBooks }
  })
});

// src/lib/mcp/tools/list-photography.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_photography_default = defineTool3({
  name: "list_photography",
  title: "List photography",
  description: "List Jiang's published landscape/city photography shown on the site, with image paths, neutral descriptions and pixel dimensions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const photos = mcpPhotos.map((p) => ({ ...p, url: mcpSite.url + p.src }));
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify({ photos, fullGallery: mcpSite.vivoGalleryUrl }, null, 2)
        }
      ],
      structuredContent: { photos, fullGallery: mcpSite.vivoGalleryUrl }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "jiang-portfolio-mcp",
  title: "Jiang \u7684\u521B\u4F5C\u4E16\u754C MCP",
  version: "0.1.0",
  instructions: "Public read-only tools for Jiang's creative portfolio (novels + landscape photography). Use `get_profile` for the creator introduction, `list_novels` for the serialized novels on \u756A\u8304\u5C0F\u8BF4 / \u4E03\u732B\u5C0F\u8BF4, and `list_photography` for the published photo set. All data mirrors the public website; there is no private or per-user data here.",
  tools: [get_profile_default, list_novels_default, list_photography_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
